replicaCount: 3
dockercfg:
  enabled: true
  image:
    pullSecret:
      registry: registry.gitlab.com
      username: josiah.choi_diginex
      password: __IMAGE_REPOSITORY_PASSWORD__

image:
  repository: registry.gitlab.com/diginexhk/esg/framework-builder-admin
  tag: dev-__CI_PIPELINE_ID__
  pullSecrets:
    - framework-builder-admin-dev-dockercfg

deployment:
  enabled: true
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 80m
      memory: 64Mi

service:
  enabled: true
  ports:
    default:
      internal: 80
      external: 80

virtualService:
  enabled: true
  hosts:
  - "framework-builder-admin.dev.dgnx.io"
  gateways:
  - default/ingressgateway-dev-dgnx-io
  routes:
    default:
      matchIPs:
      - 20.188.102.88
      - 52.184.39.156
      destination:
        host: framework-builder-admin-dev-monochart
        port: 80
